### ISSUE TITLE
Memory optimisation with batch inserts

### ISSUE THREAD

**Issue by MaximMoinat** [thehyve/delphyne#137]
**How would this feature be useful?**
When inserting many, many records from one transformation all the records are kept in a list before inserting. This will use a lot of memory. Ideally we intermittently insert the records to the database.

**Describe the solution you'd like**
An idea is to define the transformation function as a generator:
```python
def source_to_target():
    for s in df:
        # transformations
        yield Observation(...)
```

Then in delphyne:
```python
def execute_transformation(self, statement, bulk, batch_size = 10_000):
    records_to_insert = []
    for record in statement():
        records_to_insert.append(record)
        if len(records) >= batch_size:
            logger.info(f'Executing transformation: {batch_size} {statement.__name__} ')
            
            logger.info(f'Saving {len(records_to_insert)} objects')
            if bulk:
                session.bulk_save_objects(records_to_insert)
                self._collect_query_statistics_bulk_mode(session, records_to_insert,
                                                         transformation_metadata)
            else:
                session.add_all(records_to_insert)

        logger.info(f'{statement.__name__} completed with success status: '
                        f'{transformation_metadata.query_success}')
```

**Comment by Spayralbe** [comment]
@MaximMoinat Could we maybe change the expected return type of a transformation from a list to `Optional[session]`?
That way we no longer need to automagically insert the session object if it is used in the transformation, but instead make it mandatory. Instead of records.append(), it becomes session.add().
Because the session is then always available within the transformation function, you have complete control over when you want to call flush (if at all).
It would require some changes to the insert count calculation of bulk mode, but nothing too complicated.

**Comment by MaximMoinat** [comment]
I prefer to put all the database 'magic' in the wrapper. So the transformation function only focusses on the transformation logic.

Rather, I would rather make all the transformation functions generators and make the wrapper handle whether all records are inserted at once or in batches.
